### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by lfarah** [Recouse/LinearProgressBar#1]
<img width="517" alt="screen shot 2018-03-28 at 1 20 01 pm" src="https://user-images.githubusercontent.com/6511079/38042435-c1494b44-328a-11e8-82b3-6a7d3638f9f8.png">

Please fix this before we can approve [your PR in AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/2426)

**Comment by Recouse** [comment]
@lfarah Fixed. Check it out.

**Comment by lfarah** [comment]
Thanks!
