### ISSUE TITLE
Can not change color of Progress Bar

### ISSUE THREAD

**Issue by milanvthakor** [Recouse/LinearProgressBar#14]
Hi! 
I am trying to change progress bar color to yellow.
But it still showing default blue color.
I have tried the code available in Demo project but it's not working.

Thank you.

**Comment by Recouse** [comment]
Hi.
Have you tried to change `progressBarColor` value?

**Comment by milanvthakor** [comment]
Yes. I have tried to change value of progessBarColor.
But it's not changing.

**Comment by Recouse** [comment]
Can you show some code examples?

**Comment by milanvthakor** [comment]
Sorry for the late reply.

I am using below code.

let progressBar: LinearProgressBar = {
        let progressBar = LinearProgressBar()
        progressBar.progressBarColor = .systemYellow
        return progressBar
    }()

**Comment by Recouse** [comment]
Did you set a frame of `progressBar` or added some constraints?

**Comment by milanvthakor** [comment]
No. I just added programmatically upon the webView.
Here is the code.

import MaterialProgressBar

let progressBar: LinearProgressBar = {
	let lProgressBar = LinearProgressBar()
	lProgressBar.progressBarColor = .systemYellow
	return lProgressBar
}()

@IBOutlet weak var webView: WKWebView!

override func viewDidLoad() {
    super.viewDidLoad()

    //adding progress bar to webview
    webView.addSubview(progressBar)
    progressBar.startAnimating()
}


I am just displaying progressBar on top of webView

**Comment by Recouse** [comment]
You should set a frame or add constraints to place a progress bar in view.

You can also use `UIViewController` extension to show/hide a progress bar on the top of the view controller. 
From [README](https://github.com/Recouse/LinearProgressBar#usage)
```Swift
// Start animating
showProgressBar()

// Stop animating
hideProgressBar()
```

**Comment by milanvthakor** [comment]
Ok. So i have added constraint to progressBar and it is showing at correct place with the custom color.
But I notice some problem.
showProgressBar() method create the one new default progressBar by its self with the default blue color and this method is not working with progressBar i have created.

And same with hideProgressBar() method, it's only hiding progressBar created by showProgressBar() method and not hiding my custom progressBar.

I have checked in your demo example also. You can see, you have created only three progressBar, but its showing 4(blue one at top). And hide button is only hiding that blue progressBar not the other three in stackView.

**Comment by Recouse** [comment]
`showProgressBar()` and `hideProgressBar()` methods are `UIViewController` extension methods.
 `showProgressBar()` adds view on the top of the view controller, and `hideProgressBar()` removes it.

I think your issue is resolved and I can close it. Reopen this or create a new one if you have any other questions.
