### ISSUE TITLE
New animation

### ISSUE THREAD

**Issue by Recouse** [Recouse/LinearProgressBar#5]
Need to fix animation bugs in the dev branch.

**Comment by aitemr** [comment]
Hi, @Recouse 

I want to fix this bug!

**Comment by Recouse** [comment]
>Hi, @Recouse  ...

@aitemr Fell free to make pull requests

**Comment by aitemr** [comment]
Hi, @Recouse! 

I could not run project I've error 

```
Header 'Sources/LinearProgressBar-Swift.h' not found
```

Could you help me to execute project

**Comment by Recouse** [comment]
I got this error too. It's easier to remove obj-с support 😊
Just delete that files and all mentions in build settings.

**Comment by aitemr** [comment]
Thanks @Recouse!

**Comment by meshileya** [comment]
@Recouse is there a way i can actually define its position on my view while i define both height and width as well

**Comment by Recouse** [comment]
@meshileya Hi, yeah, you can. `LinearProgressBar` is a subclass of the `UIView`. So, you can work with this like with any other views.

**Comment by AntonLisovoy** [comment]
Hi there! I've created [PR](https://github.com/Recouse/LinearProgressBar/pull/10) with new animation changes

**Comment by Recouse** [comment]
Thank you @AntonLisovoy !
