### ISSUE TITLE
Cannot use it with anything other that a simple ViewController

### ISSUE THREAD

**Issue by zahariadaniel16** [Recouse/LinearProgressBar#7]
Hi,

How can I add this progress bar to a TableViewController? Or maybe a navigationController's nav bar view? I tried to do the same as you did in the example of use, but it didn't work, no progress bar. The single time when worked was when I put it in a simple View Controller with showProgressBar() and hideProgressBar(), but in my app I use other complex controllers, like TableVC, TabBarC and so on.

Thanks in advance.

**Comment by Recouse** [comment]
Hello,
I'll add extensions in the next version.

**Comment by zahariadaniel16** [comment]
Ok, thanks!
